<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wnkerr10="https://soap.api.nav.gov.hu/external/webnyk/webhibalista/1.0.0" targetNamespace="https://soap.api.nav.gov.hu/external/webnyk/webhibalista/1.0.0">
	<xs:simpleType name="Numeric10Type">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Numeric8to11Type">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{8,11}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HibaSzintType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ShortStringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FormIdType">
		<xs:annotation>
			<xs:documentation>			
			   A bizonylatrész azonosítója (nyomtatvanyazonosito) (formId)                    
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RuleIdType">
		<xs:annotation>
			<xs:documentation>			
			   A hiba egyedi azonosítója a sablonban.                 
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="HibaBaseType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
            Általános hiba leíró típus.
        </xs:documentation>
		</xs:annotation>
		<xs:attribute name="kod" type="wnkerr10:ShortStringType" use="required">
			<xs:annotation>
				<xs:documentation>
                A nyomtatványsablonban definiált hibakód.
            </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="hibaszoveg" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
                A nyomtatványsablonban definiált hibaszöveg.
            </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ruleId" type="wnkerr10:FormIdType" use="required">
			<xs:annotation>
				<xs:documentation>
                A hiba egyedi azonosítója a sablonban.
            </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="szint" type="wnkerr10:HibaSzintType">
			<xs:annotation>
				<xs:documentation>
                Hibaszint: 1=figyelmeztetés, 2=hiba, 3=súlyos hiba.
                Súlyos hiba esetén a nyomtatvány nem küldhető be.
            </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="elem" type="wnkerr10:ShortStringType">
			<xs:annotation>
				<xs:documentation>
                A hiba forrását jelentő adatmező azonosítója.
            </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="path" type="xs:string">
			<xs:annotation>
				<xs:documentation>
                A hiba forrás XPath kifejezéssel.
            </xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="AlbizonylatAzonositasType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
				  Általános kötegelt nyomtatvány albizonylat azonosítására szolgál
				  Az elemek rendre megfelelnek az adat xml-ben küldött értékeknek
				  Kizárólag 'multi' esetben
		  </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Megnevezes" type="wnkerr10:ShortStringType">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Részbizonylat azonosító megnevezése
				</xs:documentation>
			</xs:annotation>
			</xs:element>
			<xs:element name="Azonosito" type="wnkerr10:ShortStringType">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Részbizonylat azonosító 
				</xs:documentation>
			</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MunkavallaloType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
				  Járulék típusú kötegelt nyomtatvány albizonylat azonosítására szolgál
				  Az elemek rendre megfelelnek az adat xml-ben küldött értékeknek
				  Kizárólag 'multi' esetben
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Nev" type="xs:string">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Adózó neve
				</xs:documentation>
			</xs:annotation>
			</xs:element>
			<xs:element name="Adoazonosito" type="wnkerr10:Numeric10Type">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Adózó adóazonosító jele
				</xs:documentation>
			</xs:annotation>			
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdozoType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
				  Főbizonylat azonosítására szolgál
				  Az elemek rendre megfelelnek az adat xml-ben küldött értékeknek
				  'multi' esetben a főbizonylat azonosítása, 'single' esetben maga a bizonylaté
		    </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Nev" type="xs:string">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Adózó neve
				</xs:documentation>
			</xs:annotation>
			</xs:element>
			<xs:element name="Adoszam" type="wnkerr10:Numeric8to11Type" minOccurs="0">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Adózó adószáma
				</xs:documentation>
			</xs:annotation>
			</xs:element>
			<xs:element name="Adoazonosito" type="wnkerr10:Numeric10Type" minOccurs="0">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Adózó adóazonosító jele
				</xs:documentation>
			</xs:annotation>			
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AzonositasType">
		<xs:choice>
			<xs:element name="AlbizonylatAzonositas" type="wnkerr10:AlbizonylatAzonositasType">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Albizonylat azonosítás kötegelt bizonylatok esetén
				</xs:documentation>
			</xs:annotation>			
			</xs:element>
			<xs:element name="Munkavallalo" type="wnkerr10:MunkavallaloType">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Albizonylat azonosítás kötegelt bizonylatok esetén
				</xs:documentation>
			</xs:annotation>				
			</xs:element>
			<xs:element name="Adozo" type="wnkerr10:AdozoType">
			<xs:annotation>
				<xs:documentation xml:lang="hu">
					 Főbizonylat azonosítása (Kötegelt bizonylat esetén fő rekord).
				</xs:documentation>
			</xs:annotation>	
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="HibaType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
				 Hibatípus
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="wnkerr10:HibaBaseType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CsatolmanyHibaType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
				 Csatolmány hibatípus
		     </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="wnkerr10:HibaBaseType">
				<xs:attribute name="csatolmanyFajlnev" type="xs:string">
					<xs:annotation>
						<xs:documentation xml:lang="hu">
							 Csatolmány állománynév
						 </xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HibakType">
		<xs:sequence>
			<xs:element name="Hiba" type="wnkerr10:HibaType" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">
                        Egyvalidációs hiba.
                    </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CsatolmanyHibakType">
		<xs:sequence>
			<xs:element name="CsatolmanyHiba" type="wnkerr10:CsatolmanyHibaType" minOccurs="1" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="hu">
                        Egy csatolmány ellenőrzési hiba.                       
                    </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BizonylatreszType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
                  A hibalista bizonylatrészenként tagolt. Ez jellemzően a kötegelt (multi) nyomtatványok esetén értelmezhető, 'single' nyomtatványok esetén egyetlen bizonylatrészt tartalmaz
                  Megefelel az adat xml 'nyomtatvany' tagjának
                  </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Azonositas" type="wnkerr10:AzonositasType">
				<xs:annotation>
					<xs:documentation xml:lang="hu">
                      A bizonylatrész azonosítását szolgáló tag
				     </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Hibak" type="wnkerr10:HibakType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
					  A bizonylatrészhez tartozó validációs hibák listája.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="formId" type="wnkerr10:FormIdType" use="required">
			<xs:annotation>
				<xs:documentation>			
				   A bizonylatrész azonosítója (nyomtatvanyazonosito) (formId)                    
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="elemindex" type="xs:integer" use="required">
			<xs:annotation>
				<xs:documentation>				 
					A bizonylatrész sorszáma az adat xml-ben. A hibalista xml bizonylatrész szerkezete eltér az adat xml-étől. 
					A hibalista az albizonylatok (pl. 2408M) hibáival kezdődik 1-es sorszámmal.
					A főbizonylat (pl. 2408A) hibalistája az utolsó helyen van 0-s sorszámmal.
					Ez a szerkezet az ellenőrzés jellegéből adódik, minden esetben a főbizonylat ellenőrzése az utolsó
					A sorszámozásnak kizárólag 'multi' esetben van jelentősége
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="BizonylatEllenorzesType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
            A hibalista bizonylatrészenként tagolt. Ez jellemzően a kötegelt ('multi') nyomtatványok esetén értelmezhető, 'single' nyomtatványok esetén egyetlen bizonylatrészt tartalmaz
            Megefelel az adat xml 'nyomtatvany' tagjának
            </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Bizonylatresz" type="wnkerr10:BizonylatreszType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CsatolmanyFormType">
		<xs:sequence>
			<xs:element name="CsatolmanyHibak" type="wnkerr10:CsatolmanyHibakType" minOccurs="0">
				<xs:annotation>
					<xs:documentation xml:lang="hu">
                        A csatolmányok ellenőrzési hibái form típusonként.
                    </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="formId" type="wnkerr10:FormIdType" use="required">
			<xs:annotation>
				<xs:documentation>			
				   A bizonylatrész azonosítója (nyomtatvanyazonosito) (formId)                    
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="CsatolmanyEllenorzesType">
		<xs:annotation>
			<xs:documentation xml:lang="hu">
				A bizonylathoz csatolt csatolmányok ellenőrzésének eredménye.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="CsatolmanyForm" type="wnkerr10:CsatolmanyFormType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Hibalista">
		<xs:annotation>
			<xs:documentation>
				 NAV adat xml - ellenőrzés hibalista
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BizonylatEllenorzes" type="wnkerr10:BizonylatEllenorzesType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							 Bizonylat adatok ellenőrzése
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CsatolmanyEllenorzes" type="wnkerr10:CsatolmanyEllenorzesType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							 Csatolmányok ellenőrzése - a dokumentumban szereplő csatolmányokra vonatkozó adatok alapján
						</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>