<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2026

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:vmf="http://www.altova.com/MapForce/UDF/vmf" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="vmf xs">
	<xsl:template name="vmf:vmf1_inputtoresult">
		<xsl:param name="input" select="/.."/>
		<xsl:choose>
			<xsl:when test="$input='Éltv. 47/B§ (3)'">
				<xsl:value-of select="'1'"/>
			</xsl:when>
			<xsl:when test="$input='Éltv. 47/B§ (9)'">
				<xsl:value-of select="'2'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="'1'"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="vmf:vmf2_inputtoresult">
		<xsl:param name="input" select="/.."/>
		<xsl:choose>
			<xsl:when test="$input='mikorvall'">
				<xsl:value-of select="'V1'"/>
			</xsl:when>
			<xsl:when test="$input='kisterm'">
				<xsl:value-of select="'V1'"/>
			</xsl:when>
			<xsl:when test="$input='kisvall'">
				<xsl:value-of select="'V2'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="''"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<Doc_ELMDIJ xmlns="https://soap.api.nav.gov.hu/definitions/model/2.0/PEI/ELMDIJ/v0.1" xmlns:enm="https://soap.api.nav.gov.hu/definitions/model/2.0/altalanos_enum/v0.1" xmlns:common="https://soap.api.nav.gov.hu/definitions/model/2.0/common/v0.1">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">https://soap.api.nav.gov.hu/definitions/model/2.0/PEI/ELMDIJ/v0.1 file:NAV_ELMDIJ_6_0.xsd</xsl:attribute>
			<Form_ELMDIJ xmlns="">
				<Block_120001>
					<FieldGroup_120002>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var2_cur" select="."/>
							<Field_0A0001E001A>
								<xsl:value-of select="adoszam"/>
							</Field_0A0001E001A>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var3_cur" select="."/>
							<Field_0A0001E003A>
								<xsl:value-of select="felir_azonosito"/>
							</Field_0A0001E003A>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var4_cur" select="."/>
							<Field_0A0001E006A>
								<xsl:value-of select="adozo_neve"/>
							</Field_0A0001E006A>
						</xsl:for-each>
					</FieldGroup_120002>
					<FieldGroup_120003>
						<xsl:for-each select="ELMDIJ_report/ugyintezo_nev">
							<xsl:variable name="var5_cur" select="."/>
							<Field_0A0001E007A>
								<xsl:value-of select="."/>
							</Field_0A0001E007A>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report/ugyintezo_tel">
							<xsl:variable name="var6_cur" select="."/>
							<Field_0A0001E008A>
								<xsl:value-of select="."/>
							</Field_0A0001E008A>
						</xsl:for-each>
					</FieldGroup_120003>
					<FieldGroup_120006>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var7_cur" select="."/>
							<Field_0A0001F001A>
								<xsl:value-of select="kezdet_datum"/>
							</Field_0A0001F001A>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var8_cur" select="."/>
							<Field_0A0001F002A>
								<xsl:value-of select="veg_datum"/>
							</Field_0A0001F002A>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var9_cur" select="."/>
							<Field_0A0001F009A>
								<xsl:variable name="var10_nested">
									<xsl:call-template name="vmf:vmf1_inputtoresult">
										<xsl:with-param name="input" select="string(jogszabaly)"/>
									</xsl:call-template>
								</xsl:variable>
								<xsl:value-of select="$var10_nested"/>
							</Field_0A0001F009A>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report/vegso_fogyaszto">
							<xsl:variable name="var11_cur" select="."/>
							<xsl:variable name="var12_nested">
								<xsl:call-template name="vmf:vmf2_inputtoresult">
									<xsl:with-param name="input" select="string(.)"/>
								</xsl:call-template>
							</xsl:variable>
							<xsl:if test="string($var12_nested)">
								<Field_0A0001F010A>
									<xsl:variable name="var13_nested">
										<xsl:call-template name="vmf:vmf2_inputtoresult">
											<xsl:with-param name="input" select="string(.)"/>
										</xsl:call-template>
									</xsl:variable>
									<xsl:value-of select="substring($var13_nested, 2)"/>
								</Field_0A0001F010A>
							</xsl:if>
						</xsl:for-each>
					</FieldGroup_120006>
				</Block_120001>
				<Block_120022>
					<FieldGroup_120023>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var14_cur" select="."/>
							<Field_0B0001C0005BA>
								<xsl:value-of select="number(ado2)"/>
							</Field_0B0001C0005BA>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var15_cur" select="."/>
							<Field_0B0001C0004BA>
								<xsl:value-of select="number(ado1)"/>
							</Field_0B0001C0004BA>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var16_cur" select="."/>
							<xsl:for-each select="fix_ado">
								<xsl:variable name="var17_filter" select="."/>
								<xsl:if test="($var16_cur/vegso_fogyaszto)[(. = 'kisvall')]">
									<Field_0B0001C0003BA>
										<xsl:value-of select="."/>
									</Field_0B0001C0003BA>
								</xsl:if>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var18_cur" select="."/>
							<xsl:for-each select="(./fix_ado)[not(($var18_cur/vegso_fogyaszto)[(. = 'kisvall')])]">
								<xsl:variable name="var19_filter" select="."/>
								<Field_0B0001C0002BA>
									<xsl:value-of select="."/>
								</Field_0B0001C0002BA>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report/szamitott_ado">
							<xsl:variable name="var20_cur" select="."/>
							<Field_0B0001C0001BA>
								<xsl:value-of select="number(.)"/>
							</Field_0B0001C0001BA>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report">
							<xsl:variable name="var21_cur" select="."/>
							<Field_0B0001C0001AA>
								<xsl:value-of select="number(adoalap)"/>
							</Field_0B0001C0001AA>
						</xsl:for-each>
						<xsl:for-each select="ELMDIJ_report/atvallalt_adoalap">
							<xsl:variable name="var22_cur" select="."/>
							<Field_0B0001C50000A>
								<xsl:value-of select="number(.)"/>
							</Field_0B0001C50000A>
						</xsl:for-each>
					</FieldGroup_120023>
					<xsl:for-each select="ELMDIJ_report/atvallalasok">
						<xsl:variable name="var23_cur" select="."/>
						<Chain_120056>
							<xsl:for-each select="atvallalas">
								<xsl:variable name="var24_cur" select="."/>
								<Chain_elem>
									<FieldGroup_120057>
										<Field_0B0001D50004A>
											<xsl:value-of select="number(bevetel)"/>
										</Field_0B0001D50004A>
										<Field_0B0001D50007A>
											<xsl:value-of select="adoszam"/>
										</Field_0B0001D50007A>
									</FieldGroup_120057>
								</Chain_elem>
							</xsl:for-each>
						</Chain_120056>
					</xsl:for-each>
				</Block_120022>
			</Form_ELMDIJ>
		</Doc_ELMDIJ>
	</xsl:template>
</xsl:stylesheet>
