/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import hu.gov.nav.CreateBizonylatRequestBodyType;
import hu.gov.nav.CreateBizonylatResponseType;
import hu.gov.nav.GetBizonylatResponseType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BizonylatServiceApi
 */
@Ignore
public class BizonylatServiceApiTest {

    private final BizonylatServiceApi api = new BizonylatServiceApi();

    /**
     * Bizonylat.createBizonylat
     *
     * A bizonylat létrehozását és validálását biztosító művelet. Visszaadja a bizonylat státuszát és a validációs hibákat. (Letrehozva a Bizonylat.createBizonylat(messageId: char, correlationId: char, requestData: CreateBizonylatRequestType):CreateBizonylatResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBizonylatTest() {
        CreateBizonylatRequestBodyType body = null;
        String messageId = null;
        String correlationId = null;
        CreateBizonylatResponseType response = api.createBizonylat(body, messageId, correlationId);

        // TODO: test validations
    }
    /**
     * Bizonylat.getBizonylat
     *
     *  (Letrehozva a Bizonylat.getBizonylat(messageId: char, correlationId: char, ugyAzonosito: char):GetBizonylatResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBizonylatTest() {
        String ugyAzonosito = null;
        String messageId = null;
        String correlationId = null;
        GetBizonylatResponseType response = api.getBizonylat(ugyAzonosito, messageId, correlationId);

        // TODO: test validations
    }
}
