/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * BeadasiTanusitvany
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-17T13:30:43.992819144Z[GMT]")

public class BeadasiTanusitvany {
  @JsonProperty("befogadasIdopontja")
  private OffsetDateTime befogadasIdopontja = null;

  @JsonProperty("tanusitvany")
  private String tanusitvany = null;

  public BeadasiTanusitvany befogadasIdopontja(OffsetDateTime befogadasIdopontja) {
    this.befogadasIdopontja = befogadasIdopontja;
    return this;
  }

   /**
   * A befogadás időpontja
   * @return befogadasIdopontja
  **/
  @Schema(required = true, description = "A befogadás időpontja")
  public OffsetDateTime getBefogadasIdopontja() {
    return befogadasIdopontja;
  }

  public void setBefogadasIdopontja(OffsetDateTime befogadasIdopontja) {
    this.befogadasIdopontja = befogadasIdopontja;
  }

  public BeadasiTanusitvany tanusitvany(String tanusitvany) {
    this.tanusitvany = tanusitvany;
    return this;
  }

   /**
   * A befogadási a tanúsítvány. A tanúsítvány mező az elején pontosvesszővel elválasztva tartalmazza azokat az adatokat, amelyekből képezve lett. A végére kerül a maga a tanúsítvány base64 kódolva.
   * @return tanusitvany
  **/
  @Schema(required = true, description = "A befogadási a tanúsítvány. A tanúsítvány mező az elején pontosvesszővel elválasztva tartalmazza azokat az adatokat, amelyekből képezve lett. A végére kerül a maga a tanúsítvány base64 kódolva.")
  public String getTanusitvany() {
    return tanusitvany;
  }

  public void setTanusitvany(String tanusitvany) {
    this.tanusitvany = tanusitvany;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeadasiTanusitvany beadasiTanusitvany = (BeadasiTanusitvany) o;
    return Objects.equals(this.befogadasIdopontja, beadasiTanusitvany.befogadasIdopontja) &&
        Objects.equals(this.tanusitvany, beadasiTanusitvany.tanusitvany);
  }

  @Override
  public int hashCode() {
    return Objects.hash(befogadasIdopontja, tanusitvany);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeadasiTanusitvany {\n");
    
    sb.append("    befogadasIdopontja: ").append(toIndentedString(befogadasIdopontja)).append("\n");
    sb.append("    tanusitvany: ").append(toIndentedString(tanusitvany)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
