/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets BizonylatStatusz
 */
public enum BizonylatStatusz {
  VALIDACIO_ALATT("VALIDACIO_ALATT"),
  SIKERESEN_VALIDALT("SIKERESEN_VALIDALT"),
  VALIDACIOS_HIBA("VALIDACIOS_HIBA"),
  SIKERTELEN_BEKULDES("SIKERTELEN_BEKULDES"),
  SIKERTELEN_ELOELLENORZES("SIKERTELEN_ELOELLENORZES"),
  BEKULDES_ALATT("BEKULDES_ALATT"),
  SIKERESEN_BEKULDVE("SIKERESEN_BEKULDVE");

  private String value;

  BizonylatStatusz(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static BizonylatStatusz fromValue(String input) {
    for (BizonylatStatusz b : BizonylatStatusz.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
