/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.BaseResponseType;
import hu.gov.nav.BeadasiTanusitvany;
import hu.gov.nav.BizonylatStatusz;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BizonylatResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-17T13:30:43.992819144Z[GMT]")

public class BizonylatResponseType extends BaseResponseType {
  @JsonProperty("erkeztetesiSzam")
  private String erkeztetesiSzam = null;

  @JsonProperty("megjegyzes")
  private String megjegyzes = null;

  @JsonProperty("validaciosHibak")
  private byte[] validaciosHibak = null;

  @JsonProperty("beadasiTanusitvany")
  private BeadasiTanusitvany beadasiTanusitvany = null;

  @JsonProperty("bizonylatStatusz")
  private BizonylatStatusz bizonylatStatusz = null;

  public BizonylatResponseType erkeztetesiSzam(String erkeztetesiSzam) {
    this.erkeztetesiSzam = erkeztetesiSzam;
    return this;
  }

   /**
   * Érkeztetési szám
   * @return erkeztetesiSzam
  **/
  @Schema(description = "Érkeztetési szám")
  public String getErkeztetesiSzam() {
    return erkeztetesiSzam;
  }

  public void setErkeztetesiSzam(String erkeztetesiSzam) {
    this.erkeztetesiSzam = erkeztetesiSzam;
  }

  public BizonylatResponseType megjegyzes(String megjegyzes) {
    this.megjegyzes = megjegyzes;
    return this;
  }

   /**
   * A bizonylathoz fűzhető megjegyzés, ami megadása esetén bekerül a nyugtába, hasonlóan az ÁNYK-s működéshez.
   * @return megjegyzes
  **/
  @Schema(description = "A bizonylathoz fűzhető megjegyzés, ami megadása esetén bekerül a nyugtába, hasonlóan az ÁNYK-s működéshez.")
  public String getMegjegyzes() {
    return megjegyzes;
  }

  public void setMegjegyzes(String megjegyzes) {
    this.megjegyzes = megjegyzes;
  }

  public BizonylatResponseType validaciosHibak(byte[] validaciosHibak) {
    this.validaciosHibak = validaciosHibak;
    return this;
  }

   /**
   * Hibákat megállapító validáció esetén a hibákat tartalmazó xml fájl bzip2-vel tömörítve. Az xml a hibalista.xsd-vel dolgozható fel.
   * @return validaciosHibak
  **/
  @Schema(description = "Hibákat megállapító validáció esetén a hibákat tartalmazó xml fájl bzip2-vel tömörítve. Az xml a hibalista.xsd-vel dolgozható fel.")
  public byte[] getValidaciosHibak() {
    return validaciosHibak;
  }

  public void setValidaciosHibak(byte[] validaciosHibak) {
    this.validaciosHibak = validaciosHibak;
  }

  public BizonylatResponseType beadasiTanusitvany(BeadasiTanusitvany beadasiTanusitvany) {
    this.beadasiTanusitvany = beadasiTanusitvany;
    return this;
  }

   /**
   * Get beadasiTanusitvany
   * @return beadasiTanusitvany
  **/
  @Schema(description = "")
  public BeadasiTanusitvany getBeadasiTanusitvany() {
    return beadasiTanusitvany;
  }

  public void setBeadasiTanusitvany(BeadasiTanusitvany beadasiTanusitvany) {
    this.beadasiTanusitvany = beadasiTanusitvany;
  }

  public BizonylatResponseType bizonylatStatusz(BizonylatStatusz bizonylatStatusz) {
    this.bizonylatStatusz = bizonylatStatusz;
    return this;
  }

   /**
   * Get bizonylatStatusz
   * @return bizonylatStatusz
  **/
  @Schema(description = "")
  public BizonylatStatusz getBizonylatStatusz() {
    return bizonylatStatusz;
  }

  public void setBizonylatStatusz(BizonylatStatusz bizonylatStatusz) {
    this.bizonylatStatusz = bizonylatStatusz;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BizonylatResponseType bizonylatResponseType = (BizonylatResponseType) o;
    return Objects.equals(this.erkeztetesiSzam, bizonylatResponseType.erkeztetesiSzam) &&
        Objects.equals(this.megjegyzes, bizonylatResponseType.megjegyzes) &&
        Arrays.equals(this.validaciosHibak, bizonylatResponseType.validaciosHibak) &&
        Objects.equals(this.beadasiTanusitvany, bizonylatResponseType.beadasiTanusitvany) &&
        Objects.equals(this.bizonylatStatusz, bizonylatResponseType.bizonylatStatusz) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erkeztetesiSzam, megjegyzes, Arrays.hashCode(validaciosHibak), beadasiTanusitvany, bizonylatStatusz, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BizonylatResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    erkeztetesiSzam: ").append(toIndentedString(erkeztetesiSzam)).append("\n");
    sb.append("    megjegyzes: ").append(toIndentedString(megjegyzes)).append("\n");
    sb.append("    validaciosHibak: ").append(toIndentedString(validaciosHibak)).append("\n");
    sb.append("    beadasiTanusitvany: ").append(toIndentedString(beadasiTanusitvany)).append("\n");
    sb.append("    bizonylatStatusz: ").append(toIndentedString(bizonylatStatusz)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
