/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.Tomorites;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CreateBizonylatRequestType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-17T13:30:43.992819144Z[GMT]")

public class CreateBizonylatRequestType {
  @JsonProperty("bizonylatTipus")
  private String bizonylatTipus = null;

  @JsonProperty("bizonylatVerzio")
  private String bizonylatVerzio = null;

  @JsonProperty("bizonylatXml")
  private String bizonylatXml = null;

  @JsonProperty("megjegyzes")
  private String megjegyzes = null;

  @JsonProperty("signature")
  private String signature = null;

  @JsonProperty("validaciosTanusitvany")
  private String validaciosTanusitvany = null;

  @JsonProperty("tomorites")
  private Tomorites tomorites = null;

  public CreateBizonylatRequestType bizonylatTipus(String bizonylatTipus) {
    this.bizonylatTipus = bizonylatTipus;
    return this;
  }

   /**
   * A bizonylat típusa
   * @return bizonylatTipus
  **/
  @Schema(required = true, description = "A bizonylat típusa")
  public String getBizonylatTipus() {
    return bizonylatTipus;
  }

  public void setBizonylatTipus(String bizonylatTipus) {
    this.bizonylatTipus = bizonylatTipus;
  }

  public CreateBizonylatRequestType bizonylatVerzio(String bizonylatVerzio) {
    this.bizonylatVerzio = bizonylatVerzio;
    return this;
  }

   /**
   * A bizonylat verziószáma
   * @return bizonylatVerzio
  **/
  @Schema(required = true, description = "A bizonylat verziószáma")
  public String getBizonylatVerzio() {
    return bizonylatVerzio;
  }

  public void setBizonylatVerzio(String bizonylatVerzio) {
    this.bizonylatVerzio = bizonylatVerzio;
  }

  public CreateBizonylatRequestType bizonylatXml(String bizonylatXml) {
    this.bizonylatXml = bizonylatXml;
    return this;
  }

   /**
   * A bizonylat file base 64 kódolással. A tomorites paraméter adja, meg, hogy tömörtett volt-e a fájl, és ha igen, akkor milyen módon, mielőtt kódolva lett.
   * @return bizonylatXml
  **/
  @Schema(required = true, description = "A bizonylat file base 64 kódolással. A tomorites paraméter adja, meg, hogy tömörtett volt-e a fájl, és ha igen, akkor milyen módon, mielőtt kódolva lett.")
  public String getBizonylatXml() {
    return bizonylatXml;
  }

  public void setBizonylatXml(String bizonylatXml) {
    this.bizonylatXml = bizonylatXml;
  }

  public CreateBizonylatRequestType megjegyzes(String megjegyzes) {
    this.megjegyzes = megjegyzes;
    return this;
  }

   /**
   * A bizonylathoz fűzhető megjegyzés, ami megadása esetén bekerül a nyugtába, hasonlóan az ÁNYK-s működéshez.
   * @return megjegyzes
  **/
  @Schema(description = "A bizonylathoz fűzhető megjegyzés, ami megadása esetén bekerül a nyugtába, hasonlóan az ÁNYK-s működéshez.")
  public String getMegjegyzes() {
    return megjegyzes;
  }

  public void setMegjegyzes(String megjegyzes) {
    this.megjegyzes = megjegyzes;
  }

  public CreateBizonylatRequestType signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Aláírás
   * @return signature
  **/
  @Schema(required = true, description = "Aláírás")
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public CreateBizonylatRequestType validaciosTanusitvany(String validaciosTanusitvany) {
    this.validaciosTanusitvany = validaciosTanusitvany;
    return this;
  }

   /**
   * Annak a tanúsítványa, hogy a beküldött bizonylat már validálva lett. Ha létezik ilyen tanúsítvány, akkor a bizonylat a beküldés során már nem lesz validálva. Gyorsabban lefut a művelet, ami szinkronválaszt ad. A tanúsítvány mező az elején pontosvesszővel elválasztva tartalmazza azokat az adatokat, amelyekből képezve lett. A végére kerül a maga a tanúsítvány base64 kódolva.
   * @return validaciosTanusitvany
  **/
  @Schema(description = "Annak a tanúsítványa, hogy a beküldött bizonylat már validálva lett. Ha létezik ilyen tanúsítvány, akkor a bizonylat a beküldés során már nem lesz validálva. Gyorsabban lefut a művelet, ami szinkronválaszt ad. A tanúsítvány mező az elején pontosvesszővel elválasztva tartalmazza azokat az adatokat, amelyekből képezve lett. A végére kerül a maga a tanúsítvány base64 kódolva.")
  public String getValidaciosTanusitvany() {
    return validaciosTanusitvany;
  }

  public void setValidaciosTanusitvany(String validaciosTanusitvany) {
    this.validaciosTanusitvany = validaciosTanusitvany;
  }

  public CreateBizonylatRequestType tomorites(Tomorites tomorites) {
    this.tomorites = tomorites;
    return this;
  }

   /**
   * Get tomorites
   * @return tomorites
  **/
  @Schema(description = "")
  public Tomorites getTomorites() {
    return tomorites;
  }

  public void setTomorites(Tomorites tomorites) {
    this.tomorites = tomorites;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBizonylatRequestType createBizonylatRequestType = (CreateBizonylatRequestType) o;
    return Objects.equals(this.bizonylatTipus, createBizonylatRequestType.bizonylatTipus) &&
        Objects.equals(this.bizonylatVerzio, createBizonylatRequestType.bizonylatVerzio) &&
        Objects.equals(this.bizonylatXml, createBizonylatRequestType.bizonylatXml) &&
        Objects.equals(this.megjegyzes, createBizonylatRequestType.megjegyzes) &&
        Objects.equals(this.signature, createBizonylatRequestType.signature) &&
        Objects.equals(this.validaciosTanusitvany, createBizonylatRequestType.validaciosTanusitvany) &&
        Objects.equals(this.tomorites, createBizonylatRequestType.tomorites);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bizonylatTipus, bizonylatVerzio, bizonylatXml, megjegyzes, signature, validaciosTanusitvany, tomorites);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBizonylatRequestType {\n");
    
    sb.append("    bizonylatTipus: ").append(toIndentedString(bizonylatTipus)).append("\n");
    sb.append("    bizonylatVerzio: ").append(toIndentedString(bizonylatVerzio)).append("\n");
    sb.append("    bizonylatXml: ").append(toIndentedString(bizonylatXml)).append("\n");
    sb.append("    megjegyzes: ").append(toIndentedString(megjegyzes)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    validaciosTanusitvany: ").append(toIndentedString(validaciosTanusitvany)).append("\n");
    sb.append("    tomorites: ").append(toIndentedString(tomorites)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
