/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets CreateBizonylatResult
 */
public enum CreateBizonylatResult {
  ERVENYTELEN_ALAIRAS("ERVENYTELEN_ALAIRAS"),
  SIKERES("SIKERES"),
  ERVENYTELEN_BIZONYLAT_TIPUS("ERVENYTELEN_BIZONYLAT_TIPUS"),
  ERVENYTELEN_BIZONYLAT_VERZIO("ERVENYTELEN_BIZONYLAT_VERZIO"),
  HIBAS_TOMORITES("HIBAS_TOMORITES"),
  VIRUSOS_FAJL("VIRUSOS_FAJL"),
  NINCS_JOGOSULTSAG_BIZONYLATTIPUSHOZ("NINCS_JOGOSULTSAG_BIZONYLATTIPUSHOZ"),
  NINCS_JOGOSULTSAG_ADOZOHOZ("NINCS_JOGOSULTSAG_ADOZOHOZ"),
  ERVENYTELEN_ADOZO("ERVENYTELEN_ADOZO"),
  ERVENYTELEN_BEKULDO("ERVENYTELEN_BEKULDO"),
  EGYEB_HIBA("EGYEB_HIBA"),
  SIKERTELEN_VALIDACIO("SIKERTELEN_VALIDACIO"),
  EREVENYTELEN_KODOLAS("EREVENYTELEN_KODOLAS"),
  ERVENYTELEN_KARAKTER("ERVENYTELEN_KARAKTER"),
  SIKERTELEN_BEKULDES("SIKERTELEN_BEKULDES"),
  HIBAS_CSATOLMANY_MERET("HIBAS_CSATOLMANY_MERET"),
  NEM_TALALHATO_CSATOLMANY("NEM_TALALHATO_CSATOLMANY"),
  NEM_XSD_VALID_XML("NEM_XSD_VALID_XML");

  private String value;

  CreateBizonylatResult(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CreateBizonylatResult fromValue(String input) {
    for (CreateBizonylatResult b : CreateBizonylatResult.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
