/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.CreateBizonylatRequestType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CreateBizonylatRequestBodyType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-17T13:30:43.992819144Z[GMT]")

public class CreateBizonylatRequestBodyType {
  @JsonProperty("requestData")
  private CreateBizonylatRequestType requestData = null;

  public CreateBizonylatRequestBodyType requestData(CreateBizonylatRequestType requestData) {
    this.requestData = requestData;
    return this;
  }

   /**
   * Get requestData
   * @return requestData
  **/
  @Schema(required = true, description = "")
  public CreateBizonylatRequestType getRequestData() {
    return requestData;
  }

  public void setRequestData(CreateBizonylatRequestType requestData) {
    this.requestData = requestData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateBizonylatRequestBodyType createBizonylatRequestBodyType = (CreateBizonylatRequestBodyType) o;
    return Objects.equals(this.requestData, createBizonylatRequestBodyType.requestData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateBizonylatRequestBodyType {\n");
    
    sb.append("    requestData: ").append(toIndentedString(requestData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
