/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.BeadasiTanusitvany;
import hu.gov.nav.BizonylatResponseType;
import hu.gov.nav.BizonylatStatusz;
import hu.gov.nav.GetBizonylatResult;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GetBizonylatResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-17T13:30:43.992819144Z[GMT]")

public class GetBizonylatResponseType extends BizonylatResponseType {
  @JsonProperty("resultCode")
  private GetBizonylatResult resultCode = null;

  public GetBizonylatResponseType resultCode(GetBizonylatResult resultCode) {
    this.resultCode = resultCode;
    return this;
  }

   /**
   * Get resultCode
   * @return resultCode
  **/
  @Schema(description = "")
  public GetBizonylatResult getResultCode() {
    return resultCode;
  }

  public void setResultCode(GetBizonylatResult resultCode) {
    this.resultCode = resultCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBizonylatResponseType getBizonylatResponseType = (GetBizonylatResponseType) o;
    return Objects.equals(this.resultCode, getBizonylatResponseType.resultCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBizonylatResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    resultCode: ").append(toIndentedString(resultCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
