/*
 * NavM2mBizonylat
 * OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets Tomorites
 */
public enum Tomorites {
  GZIP("GZIP");

  private String value;

  Tomorites(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Tomorites fromValue(String input) {
    for (Tomorites b : Tomorites.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
