/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import hu.gov.nav.GetFileStatusResponseType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilestoreDownloadServiceApi
 */
@Ignore
public class FilestoreDownloadServiceApiTest {

    private final FilestoreDownloadServiceApi api = new FilestoreDownloadServiceApi();

    /**
     * File.getFileStatus
     *
     * Egy feltöltött fájl állapotának lekérdezése.  (Letrehozva a File.getFileStatus(fileId: char, correlationId: char, messageId: char, Authorization: char):GetFileStatusResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFileStatusTest() {
        String fileId = null;
        String messageId = null;
        String correlationId = null;
        GetFileStatusResponseType response = api.getFileStatus(fileId, messageId, correlationId);

        // TODO: test validations
    }
}
