/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import hu.gov.nav.AddFileResponseType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilestoreUploadServiceApi
 */
@Ignore
public class FilestoreUploadServiceApiTest {

    private final FilestoreUploadServiceApi api = new FilestoreUploadServiceApi();

    /**
     * File.addFile
     *
     * Egy fájl feltöltésére szolgáló művelet. A visszatérési értékben szerepel a file azonosítója, amivel a feldolgozások során hivatkozni lehet rá. (Letrehozva a File.addFile(*_/_*: file, correlationId: char, messageId: char, Authorization: char, sha256hash: char, signature: char):AddFileResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addFileTest() {
        Object body = null;
        String messageId = null;
        String correlationId = null;
        String sha256hash = null;
        String signature = null;
        AddFileResponseType response = api.addFile(body, messageId, correlationId, sha256hash, signature);

        // TODO: test validations
    }
}
