/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import hu.gov.nav.CreateTokenRequestBodyType;
import hu.gov.nav.CreateTokenResponseType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokenServiceApi
 */
@Ignore
public class TokenServiceApiTest {

    private final TokenServiceApi api = new TokenServiceApi();

    /**
     * Token.createToken
     *
     * Új token kérését biztosító művelet, amely egy belépést és egy token frissítést lehetővé tevő tokent ad vissza. (Letrehozva a Token.createToken(requestData: CreateTokenRequestType, messageId: string, correlationId: string):CreateTokenResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTokenTest() {
        CreateTokenRequestBodyType body = null;
        String messageId = null;
        String correlationId = null;
        CreateTokenResponseType response = api.createToken(body, messageId, correlationId);

        // TODO: test validations
    }
}
