/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import hu.gov.nav.ActivateUserRegistrationRequestBodyType;
import hu.gov.nav.ActivateUserRegistrationResponseType;
import hu.gov.nav.RedeemNonceRequestBodyType;
import hu.gov.nav.RedeemNonceResponseType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserregistrationServiceApi
 */
@Ignore
public class UserregistrationServiceApiTest {

    private final UserregistrationServiceApi api = new UserregistrationServiceApi();

    /**
     * Activation.activateUserRegistration
     *
     *  (Letrehozva a Activation.activateUserRegistration(requestData: ActivateUserRegistrationRequestType, messageId: char, correlationId: char, Authorization: char):ActivateUserRegistrationResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void activateUserRegistrationTest() {
        ActivateUserRegistrationRequestBodyType body = null;
        String messageId = null;
        String correlationId = null;
        ActivateUserRegistrationResponseType response = api.activateUserRegistration(body, messageId, correlationId);

        // TODO: test validations
    }
    /**
     * Nonce.redeemNonce
     *
     * Nonce beváltását biztosító művelet (Letrehozva a Nonce.redeemNonce(requestData: RedeemNonceRequestType, messageId: char, correlationId: char, Authorization: char):RedeemNonceResponseType operation-bol.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void redeemNonceTest() {
        RedeemNonceRequestBodyType body = null;
        String messageId = null;
        String correlationId = null;
        RedeemNonceResponseType response = api.redeemNonce(body, messageId, correlationId);

        // TODO: test validations
    }
}
