openapi: 3.0.0
x-generator-comment: 'Generalt service: NavM2mBizonylat'
info:
  title: NavM2mBizonylat
  description: 'OpenAPI Document NAV M2M Bizonylat szolgáltatáshoz. '
  version: '1.0'
paths:
  /NavM2mBizonylat/bizonylatService/Bizonylat/{ugyAzonosito}:
    get:
      tags:
        - BizonylatService
      summary: Bizonylat.getBizonylat
      description: >-
        A bizonylat lekérdezését biztosító művelet. Visszaadja a bizonylat
        státuszát és a validációs hibákat. (Letrehozva a
        Bizonylat.getBizonylat(messageId*: char, correlationId: char,
        ugyAzonosito: char):GetBizonylatResponseType operation-bol.)
      operationId: getBizonylat
      parameters:
        - name: messageid
          in: header
          description: Az üzenet egyedi azonosítója
          required: true
          schema:
            type: string
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            minLength: 36
            maxLength: 36
        - name: correlationId
          in: header
          description: Üzenetek összekapcsolását biztosító egyedi azonosító.
          required: false
          schema:
            type: string
            pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            minLength: 36
            maxLength: 36
      x-generator-comment: 'Operation return type: getBizonylatResponseBody'
      responses:
        '200':
          $ref: '#/components/responses/getBizonylatResponseBody'
    parameters:
      - name: ugyAzonosito
        in: path
        required: true
        description: >-
          Annak az ügynek(bizonylatbeküldés) az egyedi azonosítója, aminek a
          státuszának lekérdezése történik. Path parameterkent letrehozva!
        schema:
          type: string
  /NavM2mBizonylat/bizonylatService/Bizonylat:
    post:
      tags:
        - BizonylatService
      summary: Bizonylat.createBizonylat
      description: >-
        A bizonylat validálását és beküldését biztosító művelet. Visszaadja a
        bizonylat státuszát és a validációs hibákat, amennyiben 30 másodpercen
        belül azok előállnak. A később előálló eredmény getBizonylat művelettel
        az üzgyazonosító megadásával kérdezhető le. (Letrehozva a
        Bizonylat.createBizonylat(messageId*: char, correlationId: char,
        requestData: CreateBizonylatRequestType):CreateBizonylatResponseType
        operation-bol.)
      operationId: createBizonylat
      requestBody:
        $ref: '#/components/requestBodies/createBizonylatRequestBody'
      parameters:
        - name: messageid
          in: header
          description: Az üzenet egyedi azonosítója
          required: true
          schema:
            type: string
        - name: correlationId
          in: header
          description: Üzenetek összekapcsolását biztosító egyedi azonosító.
          required: false
          schema:
            type: string
      x-generator-comment: 'Operation return type: createBizonylatResponseBody'
      responses:
        '200':
          $ref: '#/components/responses/createBizonylatResponseBody'
    parameters: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  requestBodies:
    createBizonylatRequestBody:
      description: ''
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createBizonylatRequestBodyType'
  responses:
    getBizonylatResponseBody:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetBizonylatResponseType'
    createBizonylatResponseBody:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateBizonylatResponseType'
  schemas:
    BaseResponseType:
      type: object
      properties:
        resultMessage:
          description: Válaszüzenet
          type: string
    createBizonylatRequestBodyType:
      type: object
      properties:
        requestData:
          $ref: '#/components/schemas/CreateBizonylatRequestType'
    CreateBizonylatResponseType:
      allOf:
        - $ref: '#/components/schemas/BizonylatResponseType'
        - type: object
          properties:
            ugyAzonosito:
              description: >-
                Az ügy egyedi azonosítója. Ezzel lehet lekérdezni beküldést
                köveően a státuszt.
              type: string
              maxLength: 100
            resultCode:
              $ref: '#/components/schemas/CreateBizonylatResult'
      required:
        - ugyAzonosito
    GetBizonylatResponseType:
      allOf:
        - $ref: '#/components/schemas/BizonylatResponseType'
        - type: object
          properties:
            resultCode:
              $ref: '#/components/schemas/GetBizonylatResult'
    Tomorites:
      type: string
      enum:
        - GZIP
    BizonylatStatusz:
      type: string
      enum:
        - VALIDACIO_ALATT
        - SIKERESEN_VALIDALT
        - VALIDACIOS_HIBA
        - SIKERTELEN_BEKULDES
        - SIKERTELEN_ELOELLENORZES
        - BEKULDES_ALATT
        - SIKERESEN_BEKULDVE
    CreateBizonylatRequestType:
      type: object
      properties:
        bizonylatTipus:
          description: A bizonylat típusa
          type: string
          maxLength: 100
        bizonylatVerzio:
          description: A bizonylat verziószáma
          type: string
          maxLength: 10
          pattern: ^[A-Za-z0-9.\-_]{1,10}$
        bizonylatXml:
          description: >-
            A bizonylat file base 64 kódolással. A tomorites paraméter adja,
            meg, hogy tömörtett volt-e a fájl, és ha igen, akkor milyen módon,
            mielőtt kódolva lett.
          type: string
          format: byte
        megjegyzes:
          description: >-
            A bizonylathoz fűzhető megjegyzés, ami megadása esetén bekerül a
            nyugtába, hasonlóan az ÁNYK-s működéshez.
          type: string
          maxLength: 2000
        signature:
          description: >-
            Aláírás.  A műveletfüggő érték a bizonylat xml SHA256 hashelt
            értéke.
          type: string
          maxLength: 200
        validaciosTanusitvany:
          description: >-
            Annak a tanúsítványa, hogy a beküldött bizonylat már validálva lett.
            Ha létezik ilyen tanúsítvány, akkor a bizonylat a beküldés során már
            nem lesz validálva. Gyorsabban lefut a művelet, ami szinkronválaszt
            ad. A tanúsítvány mező az elején pontosvesszővel elválasztva
            tartalmazza azokat az adatokat, amelyekből képezve lett. A végére
            kerül a maga a tanúsítvány base64 kódolva.
          type: string
          maxLength: 500
        tomorites:
          $ref: '#/components/schemas/Tomorites'
      required:
        - bizonylatTipus
        - bizonylatVerzio
        - bizonylatXml
        - signature
    BizonylatResponseType:
      allOf:
        - $ref: '#/components/schemas/BaseResponseType'
        - type: object
          properties:
            befogadasIdopontja:
              description: A befogadás időpontja
              type: string
              format: date-time
            erkeztetesiSzam:
              description: Érkeztetési szám
              type: string
              maxLength: 100
            megjegyzes:
              description: >-
                A bizonylathoz fűzhető megjegyzés, ami megadása esetén bekerül a
                nyugtába, hasonlóan az ÁNYK-s működéshez.
              type: string
              maxLength: 2000
            validaciosHibak:
              description: >-
                Hibákat megállapító validáció esetén a hibákat tartalmazó xml
                fájl bzip2-vel tömörítve. Az xml a hibalista.xsd-vel dolgozható
                fel.
              type: string
              format: byte
            bizonylatStatusz:
              $ref: '#/components/schemas/BizonylatStatusz'
    CreateBizonylatResult:
      type: string
      enum:
        - ERVENYTELEN_ALAIRAS
        - SIKERES
        - ERVENYTELEN_BIZONYLAT_TIPUS
        - ERVENYTELEN_BIZONYLAT_VERZIO
        - HIBAS_TOMORITES
        - VIRUSOS_FAJL
        - NINCS_JOGOSULTSAG_BIZONYLATTIPUSHOZ
        - NINCS_JOGOSULTSAGA_A_BEKULDONEK
        - ERVENYTELEN_ADOZO
        - ERVENYTELEN_BEKULDO
        - EGYEB_HIBA
        - SIKERTELEN_VALIDACIO
        - ERVENYTELEN_KODOLAS
        - ERVENYTELEN_KARAKTER
        - SIKERTELEN_BEKULDES
        - HIBAS_CSATOLMANY_MERET
        - NEM_TALALHATO_CSATOLMANY
        - NEM_XSD_VALID_XML
        - HIBAS_XML_FORMATUM
    GetBizonylatResult:
      type: string
      enum:
        - SIKERES
        - NEMLETEZO_UGY_AZONOSITO
        - EGYEB_HIBA
tags:
  - name: BizonylatService
    description: ' A Bizonylat service csomagba tartozo OAS elemek'
    
servers: [
  {
    "url": https://m2m-dev.nav.gov.hu/rest-api/1.0/,
    "description": "Fejlesztői célú szolgáltatás végpont. A szolgáltatások ezen a végponton nem valós tartalommal kerülnek megvalósításra!"
  }
]

security:
  - bearerAuth: []