/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ActivateUserRegistrationResult
 */
public enum ActivateUserRegistrationResult {
  ACTIVATE_USER_REGISTRATION_SUCCESSFUL("ACTIVATE_USER_REGISTRATION_SUCCESSFUL"),
  USER_REGISTRATION_ALREADY_ACTIVATED("USER_REGISTRATION_ALREADY_ACTIVATED"),
  OTHER_ERROR("OTHER_ERROR"),
  INVALID_SIGNATURE("INVALID_SIGNATURE");

  private String value;

  ActivateUserRegistrationResult(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ActivateUserRegistrationResult fromValue(String input) {
    for (ActivateUserRegistrationResult b : ActivateUserRegistrationResult.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
