/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.ActivateUserRegistrationResult;
import hu.gov.nav.BaseResponseType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ActivateUserRegistrationResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class ActivateUserRegistrationResponseType extends BaseResponseType {
  @JsonProperty("resultCode")
  private ActivateUserRegistrationResult resultCode = null;

  public ActivateUserRegistrationResponseType resultCode(ActivateUserRegistrationResult resultCode) {
    this.resultCode = resultCode;
    return this;
  }

   /**
   * Get resultCode
   * @return resultCode
  **/
  @Schema(description = "")
  public ActivateUserRegistrationResult getResultCode() {
    return resultCode;
  }

  public void setResultCode(ActivateUserRegistrationResult resultCode) {
    this.resultCode = resultCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateUserRegistrationResponseType activateUserRegistrationResponseType = (ActivateUserRegistrationResponseType) o;
    return Objects.equals(this.resultCode, activateUserRegistrationResponseType.resultCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateUserRegistrationResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    resultCode: ").append(toIndentedString(resultCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
