/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.BaseResponseType;
import hu.gov.nav.FileUploadResult;
import hu.gov.nav.VirusScanResult;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AddFileResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class AddFileResponseType extends BaseResponseType {
  @JsonProperty("fileId")
  private String fileId = null;

  @JsonProperty("result_code")
  private FileUploadResult resultCode = null;

  @JsonProperty("virusScanResultCode")
  private VirusScanResult virusScanResultCode = null;

  public AddFileResponseType fileId(String fileId) {
    this.fileId = fileId;
    return this;
  }

   /**
   * A fájl egyedi azonosítója, ami alapján a fájlra hivatkozni lehet. 
   * @return fileId
  **/
  @Schema(description = "A fájl egyedi azonosítója, ami alapján a fájlra hivatkozni lehet. ")
  public String getFileId() {
    return fileId;
  }

  public void setFileId(String fileId) {
    this.fileId = fileId;
  }

  public AddFileResponseType resultCode(FileUploadResult resultCode) {
    this.resultCode = resultCode;
    return this;
  }

   /**
   * Get resultCode
   * @return resultCode
  **/
  @Schema(description = "")
  public FileUploadResult getResultCode() {
    return resultCode;
  }

  public void setResultCode(FileUploadResult resultCode) {
    this.resultCode = resultCode;
  }

  public AddFileResponseType virusScanResultCode(VirusScanResult virusScanResultCode) {
    this.virusScanResultCode = virusScanResultCode;
    return this;
  }

   /**
   * Get virusScanResultCode
   * @return virusScanResultCode
  **/
  @Schema(description = "")
  public VirusScanResult getVirusScanResultCode() {
    return virusScanResultCode;
  }

  public void setVirusScanResultCode(VirusScanResult virusScanResultCode) {
    this.virusScanResultCode = virusScanResultCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddFileResponseType addFileResponseType = (AddFileResponseType) o;
    return Objects.equals(this.fileId, addFileResponseType.fileId) &&
        Objects.equals(this.resultCode, addFileResponseType.resultCode) &&
        Objects.equals(this.virusScanResultCode, addFileResponseType.virusScanResultCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, resultCode, virusScanResultCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddFileResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    resultCode: ").append(toIndentedString(resultCode)).append("\n");
    sb.append("    virusScanResultCode: ").append(toIndentedString(virusScanResultCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
