/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CreateTokenRequestType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class CreateTokenRequestType {
  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("clientSecret")
  private String clientSecret = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("username")
  private String username = null;

  public CreateTokenRequestType clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Kliens azonosító
   * @return clientId
  **/
  @Schema(required = true, description = "Kliens azonosító")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public CreateTokenRequestType clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Kliens jelszó
   * @return clientSecret
  **/
  @Schema(required = true, description = "Kliens jelszó")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public CreateTokenRequestType password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Felhasználó jelszó
   * @return password
  **/
  @Schema(required = true, description = "Felhasználó jelszó")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public CreateTokenRequestType username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Felhasználónév
   * @return username
  **/
  @Schema(required = true, description = "Felhasználónév")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTokenRequestType createTokenRequestType = (CreateTokenRequestType) o;
    return Objects.equals(this.clientId, createTokenRequestType.clientId) &&
        Objects.equals(this.clientSecret, createTokenRequestType.clientSecret) &&
        Objects.equals(this.password, createTokenRequestType.password) &&
        Objects.equals(this.username, createTokenRequestType.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, password, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTokenRequestType {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
