/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.BaseResponseType;
import hu.gov.nav.VirusScanResult;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * GetFileStatusResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class GetFileStatusResponseType extends BaseResponseType {
  @JsonProperty("retentionTime")
  private OffsetDateTime retentionTime = null;

  @JsonProperty("resultCode")
  private VirusScanResult resultCode = null;

  public GetFileStatusResponseType retentionTime(OffsetDateTime retentionTime) {
    this.retentionTime = retentionTime;
    return this;
  }

   /**
   * Az állomány garantált megőrzési ideje.
   * @return retentionTime
  **/
  @Schema(description = "Az állomány garantált megőrzési ideje.")
  public OffsetDateTime getRetentionTime() {
    return retentionTime;
  }

  public void setRetentionTime(OffsetDateTime retentionTime) {
    this.retentionTime = retentionTime;
  }

  public GetFileStatusResponseType resultCode(VirusScanResult resultCode) {
    this.resultCode = resultCode;
    return this;
  }

   /**
   * Get resultCode
   * @return resultCode
  **/
  @Schema(description = "")
  public VirusScanResult getResultCode() {
    return resultCode;
  }

  public void setResultCode(VirusScanResult resultCode) {
    this.resultCode = resultCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFileStatusResponseType getFileStatusResponseType = (GetFileStatusResponseType) o;
    return Objects.equals(this.retentionTime, getFileStatusResponseType.retentionTime) &&
        Objects.equals(this.resultCode, getFileStatusResponseType.resultCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retentionTime, resultCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFileStatusResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    retentionTime: ").append(toIndentedString(retentionTime)).append("\n");
    sb.append("    resultCode: ").append(toIndentedString(resultCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
