/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets RedeemNonceResult
 */
public enum RedeemNonceResult {
  REDEEM_NONCE_SUCCESSFUL("REDEEM_NONCE_SUCCESSFUL"),
  INVALID_NONCE("INVALID_NONCE"),
  OTHER_ERROR("OTHER_ERROR");

  private String value;

  RedeemNonceResult(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static RedeemNonceResult fromValue(String input) {
    for (RedeemNonceResult b : RedeemNonceResult.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
