/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.BaseResponseType;
import hu.gov.nav.RedeemNonceResult;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * RedeemNonceResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class RedeemNonceResponseType extends BaseResponseType {
  @JsonProperty("signatureKeySecondPart")
  private String signatureKeySecondPart = null;

  @JsonProperty("resultCode")
  private RedeemNonceResult resultCode = null;

  public RedeemNonceResponseType signatureKeySecondPart(String signatureKeySecondPart) {
    this.signatureKeySecondPart = signatureKeySecondPart;
    return this;
  }

   /**
   * Aláírókulcs második fele
   * @return signatureKeySecondPart
  **/
  @Schema(description = "Aláírókulcs második fele")
  public String getSignatureKeySecondPart() {
    return signatureKeySecondPart;
  }

  public void setSignatureKeySecondPart(String signatureKeySecondPart) {
    this.signatureKeySecondPart = signatureKeySecondPart;
  }

  public RedeemNonceResponseType resultCode(RedeemNonceResult resultCode) {
    this.resultCode = resultCode;
    return this;
  }

   /**
   * Get resultCode
   * @return resultCode
  **/
  @Schema(description = "")
  public RedeemNonceResult getResultCode() {
    return resultCode;
  }

  public void setResultCode(RedeemNonceResult resultCode) {
    this.resultCode = resultCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedeemNonceResponseType redeemNonceResponseType = (RedeemNonceResponseType) o;
    return Objects.equals(this.signatureKeySecondPart, redeemNonceResponseType.signatureKeySecondPart) &&
        Objects.equals(this.resultCode, redeemNonceResponseType.resultCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureKeySecondPart, resultCode, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedeemNonceResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    signatureKeySecondPart: ").append(toIndentedString(signatureKeySecondPart)).append("\n");
    sb.append("    resultCode: ").append(toIndentedString(resultCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
