/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * RedeemNonceRequestType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class RedeemNonceRequestType {
  @JsonProperty("nonce")
  private String nonce = null;

  public RedeemNonceRequestType nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

   /**
   * Nonce. Az aláírókulcs második felének elkérésére alkalmas ideiglenes jelszó.
   * @return nonce
  **/
  @Schema(required = true, description = "Nonce. Az aláírókulcs második felének elkérésére alkalmas ideiglenes jelszó.")
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedeemNonceRequestType redeemNonceRequestType = (RedeemNonceRequestType) o;
    return Objects.equals(this.nonce, redeemNonceRequestType.nonce);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nonce);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedeemNonceRequestType {\n");
    
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
