/*
 * NavM2mCommon
 * OpenAPI Document NAV M2M Common szolgáltatáshoz. Claim Check integrációs minta használatához kialakított fájl tároló szolgáltatás. 
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.gov.nav;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.gov.nav.BaseResponseType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TokenBaseResponseType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-02-03T10:46:30.977683945Z[GMT]")

public class TokenBaseResponseType extends BaseResponseType {
  @JsonProperty("accessToken")
  private String accessToken = null;

  public TokenBaseResponseType accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * A hozzáférést biztosító token
   * @return accessToken
  **/
  @Schema(description = "A hozzáférést biztosító token")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenBaseResponseType tokenBaseResponseType = (TokenBaseResponseType) o;
    return Objects.equals(this.accessToken, tokenBaseResponseType.accessToken) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenBaseResponseType {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
